openapi: 3.1.0
info:
  version: 1.0.0
  title: Products API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Products docs
tags:
  - name: Products
    description: Products operations.
servers:
  - url: http://localhost:3000
paths:
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
  /products/{productId}:
    get: 
      $ref: ../swagger/paths/products/{productId}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
